version: "3"
services:
  r-runner:
    image: armr:latest
    hostname: boss
    ports:
      - "11317:11317"
    networks:
      - spark-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.role==manager
    volumes:
      - gfs2:/data
      - /var/run/docker.sock:/var/run/docker.sock
  r-worker:
    image: armr:latest
    ports:
      - "11318-11320:11317"
    networks:
      - spark-net
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.role==worker
    volumes:
      - gfs2:/data
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  spark-net:
    external: true

volumes:
  gfs2:
    driver: glust
